### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TheTeaCup** [helmasaur/zodiac-signs#18]
I really love this package it's so easy to use but I have a suggestion, you should include facts with each sign. Also, I would really love to help you with this project if you are up to!

**Comment by Helmasaur** [comment]
First of all, thanks for the comment!

I planned about adding more informations (example: #5) on each signs but didn't get the time to work on it yet. What kind of facts would you like to be added?

**Comment by TheTeaCup** [comment]
I was thining like personality facts, Kind, Funny, ect.

**Comment by Helmasaur** [comment]
I am okay with that. Although, are those informations different regarding of the source or country or are they kind of ”universal” data?

**Comment by TheTeaCup** [comment]
universal data

**Comment by Helmasaur** [comment]
Then I'm good with it! Otherwise, I was thinking about the possibility to add a way to anyone to add personal data and that the package manages it itself!

**Comment by TheTeaCup** [comment]
Oh cool! Sorry for such a late response, I've been busy. I was wondering if we could implement Sun and Moon signs also?

**Comment by helmasaur** [comment]
May I ask you why you marked it as complete?

Anyway, I'll soon update the package with more information on each signs.

Sorry for the delay, but I'm on it!
