### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by redwerkz** [helmasaur/zodiac-signs#42]
> Both Conservancy and the Git project are aware that the initial branch name, ‘master’, is offensive to some people and we empathize with those hurt by the use of that term.

https://sfconservancy.org/news/2020/jun/23/gitbranchname/
https://github.com/github/renaming

**Comment by helmasaur** [comment]
Thank you for this piece of information. I'll read the articles you linked!

**Comment by helmasaur** [comment]
Done!
